(define (make-monitored f)
  (let ((calls-count 0))
    (define (call-f v)
      (f v))
    (define (dispatch in)
      (cond ((eq? in 'how-many-calls?) calls-count)
            ((eq? in 'reset-count) (set! calls-count 0))
            (else (begin (set! calls-count (+ calls-count 1))
                         (call-f in)))))
    dispatch))

;; (define s (make-monitored sqrt))
;; (s 100)
;; (s 'how-many-calls?)
